#pragma once

#include <unordered_map>
#include <string>

extern "C" {
#include <linux/input.h>
}

#include "Language.hpp"

class Decoder
{
public:
        /**
         * @brief Метод для получения символа русского языка по коду клавиши.
         */
        static const std::string getKeycodeReprRu(int keycode);

        /**
         * @brief Метод для получения символа английского языка по коду клавиши.
         */
        static const std::string getKeycodeReprEn(int keycode);

        /**
         * @brief Обобщённый метод для получения печатного представления символа клавиши с учётом
         * переданного языка.
         */
        static const std::string getKeycodeRepr(int keycode, Language lang);

        /**
         * @brief Метод, определяющий, что клавиша является буквой.
         */
        static bool isLetter(int keycode);

        /**
         * @brief Метод, определяющий, что клавиша является цифрой.
         */
        static bool isDigit(int keycode);

        /**
         * @brief Метод, определяющий, что клавиша является одним из пробельных символов: пробел,
         * Enter, таб.
         */
        static bool isWhitespace(int keycode);
private:
        static const std::vector<int> allKeys = {
                KEY_ESC,
                KEY_1,
                KEY_2,
                KEY_3,
                KEY_4,
                KEY_5,
                KEY_6,
                KEY_7,
                KEY_8,
                KEY_9,
                KEY_0,
                KEY_MINUS,
                KEY_EQUAL,
                KEY_BACKSPACE,
                KEY_TAB,
                KEY_Q,
                KEY_W,
                KEY_E,
                KEY_R,
                KEY_T,
                KEY_Y,
                KEY_U,
                KEY_I,
                KEY_O,
                KEY_P,
                KEY_LEFTBRACE,
                KEY_RIGHTBRACE,
                KEY_ENTER,
                KEY_LEFTCTRL,
                KEY_A,
                KEY_S,
                KEY_D,
                KEY_F,
                KEY_G,
                KEY_H,
                KEY_J,
                KEY_K,
                KEY_L,
                KEY_SEMICOLON,
                KEY_APOSTROPHE,
                KEY_GRAVE,
                KEY_LEFTSHIFT,
                KEY_BACKSLASH,
                KEY_Z,
                KEY_X,
                KEY_C,
                KEY_V,
                KEY_B,
                KEY_N,
                KEY_M,
                KEY_COMMA,
                KEY_DOT,
                KEY_SLASH,
                KEY_RIGHTSHIFT,
                KEY_KPASTERISK,
                KEY_LEFTALT,
                KEY_SPACE,
                KEY_CAPSLOCK,
                KEY_F1,
                KEY_F2,
                KEY_F3,
                KEY_F4,
                KEY_F5,
                KEY_F6,
                KEY_F7,
                KEY_F8,
                KEY_F9,
                KEY_F10,
                KEY_NUMLOCK,
                KEY_SCROLLLOCK,
                KEY_KP7,
                KEY_KP8,
                KEY_KP9,
                KEY_KPMINUS,
                KEY_KP4,
                KEY_KP5,
                KEY_KP6,
                KEY_KPPLUS,
                KEY_KP1,
                KEY_KP2,
                KEY_KP3,
                KEY_KP0,
                KEY_KPDOT,
                KEY_ZENKAKUHANKAKU,
                KEY_102ND,
                KEY_F11,
                KEY_F12,
                KEY_RO,
                KEY_KATAKANA,
                KEY_HIRAGANA,
                KEY_HENKAN,
                KEY_KATAKANAHIRAGANA,
                KEY_MUHENKAN,
                KEY_KPJPCOMMA,
                KEY_KPENTER,
                KEY_RIGHTCTRL,
                KEY_KPSLASH,
                KEY_SYSRQ,
                KEY_RIGHTALT,
                KEY_LINEFEED,
                KEY_HOME,
                KEY_UP,
                KEY_PAGEUP,
                KEY_LEFT,
                KEY_RIGHT,
                KEY_END,
                KEY_DOWN,
                KEY_PAGEDOWN,
                KEY_INSERT,
                KEY_DELETE,
                KEY_MACRO,
                KEY_MUTE,
                KEY_VOLUMEDOWN,
                KEY_VOLUMEUP,
                KEY_POWER,
                KEY_KPEQUAL,
                KEY_KPPLUSMINUS,
                KEY_PAUSE,
                KEY_SCALE,
                KEY_KPCOMMA,
                KEY_HANGEUL,
                KEY_HANGUEL,
                KEY_HANJA,
                KEY_YEN,
                KEY_LEFTMETA,
                KEY_RIGHTMETA,
                KEY_COMPOSE,
                KEY_STOP,
                KEY_AGAIN,
                KEY_PROPS,
                KEY_UNDO,
                KEY_FRONT,
                KEY_COPY,
                KEY_OPEN,
                KEY_PASTE,
                KEY_FIND,
                KEY_CUT,
                KEY_HELP,
                KEY_MENU,
                KEY_CALC,
                KEY_SETUP,
                KEY_SLEEP,
                KEY_WAKEUP,
                KEY_FILE,
                KEY_SENDFILE,
                KEY_DELETEFILE,
                KEY_XFER,
                KEY_PROG1,
                KEY_PROG2,
                KEY_WWW,
                KEY_MSDOS,
                KEY_COFFEE,
                KEY_SCREENLOCK,
                KEY_ROTATE_DISPLAY,
                KEY_DIRECTION,
                KEY_CYCLEWINDOWS,
                KEY_MAIL,
                KEY_BOOKMARKS,
                KEY_COMPUTER,
                KEY_BACK,
                KEY_FORWARD,
                KEY_CLOSECD,
                KEY_EJECTCD,
                KEY_EJECTCLOSECD,
                KEY_NEXTSONG,
                KEY_PLAYPAUSE,
                KEY_PREVIOUSSONG,
                KEY_STOPCD,
                KEY_RECORD,
                KEY_REWIND,
                KEY_PHONE,
                KEY_ISO,
                KEY_CONFIG,
                KEY_HOMEPAGE,
                KEY_REFRESH,
                KEY_EXIT,
                KEY_MOVE,
                KEY_EDIT,
                KEY_SCROLLUP,
                KEY_SCROLLDOWN,
                KEY_KPLEFTPAREN,
                KEY_KPRIGHTPAREN,
                KEY_NEW,
                KEY_REDO,
                KEY_F13,
                KEY_F14,
                KEY_F15,
                KEY_F16,
                KEY_F17,
                KEY_F18,
                KEY_F19,
                KEY_F20,
                KEY_F21,
                KEY_F22,
                KEY_F23,
                KEY_F24,
                KEY_PLAYCD,
                KEY_PAUSECD,
                KEY_PROG3,
                KEY_PROG4,
                KEY_DASHBOARD,
                KEY_SUSPEND,
                KEY_CLOSE,
                KEY_PLAY,
                KEY_FASTFORWARD,
                KEY_BASSBOOST,
                KEY_PRINT,
                KEY_HP,
                KEY_CAMERA,
                KEY_SOUND,
                KEY_QUESTION,
                KEY_EMAIL,
                KEY_CHAT,
                KEY_SEARCH,
                KEY_CONNECT,
                KEY_FINANCE,
                KEY_SPORT,
                KEY_SHOP,
                KEY_ALTERASE,
                KEY_CANCEL,
                KEY_BRIGHTNESSDOWN,
                KEY_BRIGHTNESSUP,
                KEY_MEDIA,
                KEY_SWITCHVIDEOMODE,
                KEY_KBDILLUMTOGGLE,
                KEY_KBDILLUMDOWN,
                KEY_KBDILLUMUP,
                KEY_SEND,
                KEY_REPLY,
                KEY_FORWARDMAIL,
                KEY_SAVE,
                KEY_DOCUMENTS,
                KEY_BATTERY,
                KEY_BLUETOOTH,
                KEY_WLAN,
                KEY_UWB,
                KEY_UNKNOWN,
                KEY_VIDEO_NEXT,
                KEY_VIDEO_PREV,
                KEY_BRIGHTNESS_CYCLE,
                KEY_BRIGHTNESS_AUTO,
                KEY_BRIGHTNESS_ZERO,
                KEY_DISPLAY_OFF,
                KEY_WWAN,
                KEY_WIMAX,
                KEY_RFKILL,
                KEY_MICMUTE,
                KEY_DATA,
                KEY_ONSCREEN_KEYBOARD,
                KEY_AUDIO_DESC,
                KEY_3D_MODE,
                KEY_NEXT_FAVORITE,
                KEY_STOP_RECORD,
                KEY_PAUSE_RECORD,
                KEY_VOD,
                KEY_UNMUTE,
                KEY_FASTREVERSE,
                KEY_SLOWREVERSE,
                KEY_RIGHT_UP,
                KEY_RIGHT_DOWN,
                KEY_LEFT_UP,
                KEY_LEFT_DOWN,
                KEY_ROOT_MENU,
                KEY_MEDIA_TOP_MENU,
                KEY_NUMERIC_11,
                KEY_NUMERIC_12,
                KEY_ALS_TOGGLE,
                KEY_ROTATE_LOCK_TOGGLE,
                KEY_BUTTONCONFIG,
                KEY_TASKMANAGER,
                KEY_JOURNAL,
                KEY_CONTROLPANEL,
                KEY_APPSELECT,
                KEY_SCREENSAVER,
                KEY_VOICECOMMAND,
                KEY_ASSISTANT,
                KEY_KBD_LAYOUT_NEXT,
                KEY_BRIGHTNESS_MIN,
                KEY_BRIGHTNESS_MAX,
                KEY_KBDINPUTASSIST_PREV,
                KEY_KBDINPUTASSIST_NEXT,
                KEY_KBDINPUTASSIST_PREVGROUP,
                KEY_KBDINPUTASSIST_NEXTGROUP,
                KEY_KBDINPUTASSIST_ACCEPT,
                KEY_KBDINPUTASSIST_CANCEL,
                KEY_OK,
                KEY_SELECT,
                KEY_GOTO,
                KEY_CLEAR,
                KEY_POWER2,
                KEY_OPTION,
                KEY_INFO,
                KEY_TIME,
                KEY_VENDOR,
                KEY_ARCHIVE,
                KEY_PROGRAM,
                KEY_CHANNEL,
                KEY_FAVORITES,
                KEY_EPG,
                KEY_PVR,
                KEY_MHP,
                KEY_LANGUAGE,
                KEY_TITLE,
                KEY_SUBTITLE,
                KEY_ANGLE,
                KEY_FULL_SCREEN,
                KEY_ZOOM,
                KEY_MODE,
                KEY_KEYBOARD,
                KEY_ASPECT_RATIO,
                KEY_SCREEN,
                KEY_PC,
                KEY_TV,
                KEY_TV2,
                KEY_VCR,
                KEY_VCR2,
                KEY_SAT,
                KEY_SAT2,
                KEY_CD,
                KEY_TAPE,
                KEY_RADIO,
                KEY_TUNER,
                KEY_PLAYER,
                KEY_TEXT,
                KEY_DVD,
                KEY_AUX,
                KEY_MP3,
                KEY_AUDIO,
                KEY_VIDEO,
                KEY_DIRECTORY,
                KEY_LIST,
                KEY_MEMO,
                KEY_CALENDAR,
                KEY_RED,
                KEY_GREEN,
                KEY_YELLOW,
                KEY_BLUE,
                KEY_CHANNELUP,
                KEY_CHANNELDOWN,
                KEY_FIRST,
                KEY_LAST,
                KEY_AB,
                KEY_NEXT,
                KEY_RESTART,
                KEY_SLOW,
                KEY_SHUFFLE,
                KEY_BREAK,
                KEY_PREVIOUS,
                KEY_DIGITS,
                KEY_TEEN,
                KEY_TWEN,
                KEY_VIDEOPHONE,
                KEY_GAMES,
                KEY_ZOOMIN,
                KEY_ZOOMOUT,
                KEY_ZOOMRESET,
                KEY_WORDPROCESSOR,
                KEY_EDITOR,
                KEY_SPREADSHEET,
                KEY_GRAPHICSEDITOR,
                KEY_PRESENTATION,
                KEY_DATABASE,
                KEY_NEWS,
                KEY_VOICEMAIL,
                KEY_ADDRESSBOOK,
                KEY_MESSENGER,
                KEY_DISPLAYTOGGLE,
                KEY_BRIGHTNESS_TOGGLE,
                KEY_SPELLCHECK,
                KEY_LOGOFF,
                KEY_DOLLAR,
                KEY_EURO,
                KEY_FRAMEBACK,
                KEY_FRAMEFORWARD,
                KEY_CONTEXT_MENU,
                KEY_MEDIA_REPEAT,
                KEY_10CHANNELSUP,
                KEY_10CHANNELSDOWN,
                KEY_IMAGES,
                KEY_DEL_EOL,
                KEY_DEL_EOS,
                KEY_INS_LINE,
                KEY_DEL_LINE,
                KEY_FN,
                KEY_FN_ESC,
                KEY_FN_F1,
                KEY_FN_F2,
                KEY_FN_F3,
                KEY_FN_F4,
                KEY_FN_F5,
                KEY_FN_F6,
                KEY_FN_F7,
                KEY_FN_F8,
                KEY_FN_F9,
                KEY_FN_F10,
                KEY_FN_F11,
                KEY_FN_F12,
                KEY_FN_1,
                KEY_FN_2,
                KEY_FN_D,
                KEY_FN_E,
                KEY_FN_F,
                KEY_FN_S,
                KEY_FN_B,
                KEY_BRL_DOT1,
                KEY_BRL_DOT2,
                KEY_BRL_DOT3,
                KEY_BRL_DOT4,
                KEY_BRL_DOT5,
                KEY_BRL_DOT6,
                KEY_BRL_DOT7,
                KEY_BRL_DOT8,
                KEY_BRL_DOT9,
                KEY_BRL_DOT10,
                KEY_NUMERIC_0,
                KEY_NUMERIC_1,
                KEY_NUMERIC_2,
                KEY_NUMERIC_3,
                KEY_NUMERIC_4,
                KEY_NUMERIC_5,
                KEY_NUMERIC_6,
                KEY_NUMERIC_7,
                KEY_NUMERIC_8,
                KEY_NUMERIC_9,
                KEY_NUMERIC_STAR,
                KEY_NUMERIC_POUND,
                KEY_NUMERIC_A,
                KEY_NUMERIC_B,
                KEY_NUMERIC_C,
                KEY_NUMERIC_D,
                KEY_CAMERA_FOCUS,
                KEY_WPS_BUTTON,
                KEY_TOUCHPAD_TOGGLE,
                KEY_TOUCHPAD_ON,
                KEY_TOUCHPAD_OFF,
                KEY_CAMERA_ZOOMIN,
                KEY_CAMERA_ZOOMOUT,
                KEY_CAMERA_UP,
                KEY_CAMERA_DOWN,
                KEY_CAMERA_LEFT,
                KEY_CAMERA_RIGHT,
                KEY_ATTENDANT_ON,
                KEY_ATTENDANT_OFF,
                KEY_ATTENDANT_TOGGLE,
                KEY_LIGHTS_TOGGLE,

        // XXX: Do not change the order of the version checks, they should be in
        // increasing order.

        #if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 5, 0)
                KEY_PRIVACY_SCREEN_TOGGLE,

                KEY_MACRO1,
                KEY_MACRO2,
                KEY_MACRO3,
                KEY_MACRO4,
                KEY_MACRO5,
                KEY_MACRO6,
                KEY_MACRO7,
                KEY_MACRO8,
                KEY_MACRO9,
                KEY_MACRO10,
                KEY_MACRO11,
                KEY_MACRO12,
                KEY_MACRO13,
                KEY_MACRO14,
                KEY_MACRO15,
                KEY_MACRO16,
                KEY_MACRO17,
                KEY_MACRO18,
                KEY_MACRO19,
                KEY_MACRO20,
                KEY_MACRO21,
                KEY_MACRO22,
                KEY_MACRO23,
                KEY_MACRO24,
                KEY_MACRO25,
                KEY_MACRO26,
                KEY_MACRO27,
                KEY_MACRO28,
                KEY_MACRO29,
                KEY_MACRO30,

                KEY_MACRO_RECORD_START,
                KEY_MACRO_RECORD_STOP,
                KEY_MACRO_PRESET_CYCLE,
                KEY_MACRO_PRESET1,
                KEY_MACRO_PRESET2,
                KEY_MACRO_PRESET3,
        #endif

        #if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 6, 0)
                KEY_SELECTIVE_SCREENSHOT,
        #endif

        #if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0)
                KEY_NOTIFICATION_CENTER,
                KEY_PICKUP_PHONE,
                KEY_HANGUP_PHONE,
                KEY_FN_RIGHT_SHIFT,
        #endif
        };

        static const std::unordered_map<int, std::string> keycodesToRuReprTable = {
                {1,             "esc"},
                {2,             "1"},
                {3,             "2"},
                {4,             "3"},
                {5,             "4"},
                {6,             "5"},
                {7,             "6"},
                {8,             "7"},
                {9,             "8"},
                {10,            "9"},
                {11,            "0"},
                {12,            "minus"},
                {13,            "equal"},
                {14,            "backspace"},
                {15,            "tab"},
                {16,            "й"},
                {17,            "ц"},
                {18,            "у"},
                {19,            "к"},
                {20,            "е"},
                {21,            "н"},
                {22,            "г"},
                {23,            "ш"},
                {24,            "щ"},
                {25,            "з"},
                {26,            "х"},
                {27,            "ъ"},
                {28,            "enter"},
                {29,            "leftctrl"},
                {30,            "ф"},
                {31,            "ы"},
                {32,            "в"},
                {33,            "а"},
                {34,            "п"},
                {35,            "р"},
                {36,            "о"},
                {37,            "л"},
                {38,            "д"},
                {39,            "ж"},
                {40,            "э"},
                {41,            "grave"},
                {42,            "leftshift"},
                {43,            "backslash"},
                {44,            "я"},
                {45,            "ч"},
                {46,            "с"},
                {47,            "м"},
                {48,            "и"},
                {49,            "т"},
                {50,            "ь"},
                {51,            "б"},
                {52,            "ю"},
                {53,            "."},
                {54,            "rightshift"},
                {55,            "kpasterisk"},
                {56,            "leftalt"},
                {57,            "space"},
                {58,            "capslock"},
                {59,            "f1"},
                {60,            "f2"},
                {61,            "f3"},
                {62,            "f4"},
                {63,            "f5"},
                {64,            "f6"},
                {65,            "f7"},
                {66,            "f8"},
                {67,            "f9"},
                {68,            "f10"},
                {69,            "numlock"},
                {70,            "scrolllock"},
                {71,            "kp7"},
                {72,            "kp8"},
                {73,            "kp9"},
                {74,            "kpminus"},
                {75,            "kp4"},
                {76,            "kp5"},
                {77,            "kp6"},
                {78,            "kpplus"},
                {79,            "kp1"},
                {80,            "kp2"},
                {81,            "kp3"},
                {82,            "kp0"},
                {83,            "kpdot"},
                {85,            "zenkakuhankaku"},
                {86,            "102nd"},
                {87,            "f11"},
                {88,            "f12"},
                {89,            "ro"},
                {90,            "katakana"},
                {91,            "hiragana"},
                {92,            "henkan"},
                {93,            "katakanahiragana"},
                {94,            "muhenkan"},
                {95,            "kpjpcomma"},
                {96,            "kpenter"},
                {97,            "rightctrl"},
                {98,            "kpslash"},
                {99,            "sysrq"},
                {100,           "rightalt"},
                {101,           "linefeed"},
                {102,           "home"},
                {103,           "up"},
                {104,           "pageup"},
                {105,           "left"},
                {106,           "right"},
                {107,           "end"},
                {108,           "down"},
                {109,           "pagedown"},
                {110,           "insert"},
                {111,           "delete"},
                {112,           "macro"},
                {113,           "mute"},
                {114,           "volumedown"},
                {115,           "volumeup"},
                {116,           "power"},
                {117,           "kpequal"},
                {118,           "kpplusminus"},
                {119,           "pause"},
                {120,           "scale"},
                {121,           "kpcomma"},
                {122,           "hangeul"},
                {123,           "hanja"},
                {124,           "yen"},
                {125,           "leftmeta"},
                {126,           "rightmeta"},
                {127,           "compose"},
                {128,           "stop"},
                {129,           "again"},
                {130,           "props"},
                {131,           "undo"},
                {132,           "front"},
                {133,           "copy"},
                {134,           "open"},
                {135,           "paste"},
                {136,           "find"},
                {137,           "cut"},
                {138,           "help"},
                {139,           "menu"},
                {140,           "calc"},
                {141,           "setup"},
                {142,           "sleep"},
                {143,           "wakeup"},
                {144,           "file"},
                {145,           "sendfile"},
                {146,           "deletefile"},
                {147,           "xfer"},
                {148,           "prog1"},
                {149,           "prog2"},
                {150,           "www"},
                {151,           "msdos"},
                {152,           "coffee"},
                {153,           "rotate_display"},
                {154,           "cyclewindows"},
                {155,           "mail"},
                {156,           "bookmarks"},
                {157,           "computer"},
                {158,           "back"},
                {159,           "forward"},
                {160,           "closecd"},
                {161,           "ejectcd"},
                {162,           "ejectclosecd"},
                {163,           "nextsong"},
                {164,           "playpause"},
                {165,           "previoussong"},
                {166,           "stopcd"},
                {167,           "record"},
                {168,           "rewind"},
                {169,           "phone"},
                {170,           "iso"},
                {171,           "config"},
                {172,           "homepage"},
                {173,           "refresh"},
                {174,           "exit"},
                {175,           "move"},
                {176,           "edit"},
                {177,           "scrollup"},
                {178,           "scrolldown"},
                {179,           "kpleftparen"},
                {180,           "kprightparen"},
                {181,           "new"},
                {182,           "redo"},
                {183,           "f13"},
                {184,           "f14"},
                {185,           "f15"},
                {186,           "f16"},
                {187,           "f17"},
                {188,           "f18"},
                {189,           "f19"},
                {190,           "f20"},
                {191,           "f21"},
                {192,           "f22"},
                {193,           "f23"},
                {194,           "f24"},
                {200,           "playcd"},
                {201,           "pausecd"},
                {202,           "prog3"},
                {203,           "prog4"},
                {204,           "dashboard"},
                {205,           "suspend"},
                {206,           "close"},
                {207,           "play"},
                {208,           "fastforward"},
                {209,           "bassboost"},
                {210,           "print"},
                {211,           "hp"},
                {212,           "camera"},
                {213,           "sound"},
                {214,           "question"},
                {215,           "email"},
                {216,           "chat"},
                {217,           "search"},
                {218,           "connect"},
                {219,           "finance"},
                {220,           "sport"},
                {221,           "shop"},
                {222,           "alterase"},
                {223,           "cancel"},
                {224,           "brightnessdown"},
                {225,           "brightnessup"},
                {226,           "media"},
                {227,           "switchvideomode"},
                {228,           "kbdillumtoggle"},
                {229,           "kbdillumdown"},
                {230,           "kbdillumup"},
                {231,           "send"},
                {232,           "reply"},
                {233,           "forwardmail"},
                {234,           "save"},
                {235,           "documents"},
                {236,           "battery"},
                {237,           "bluetooth"},
                {238,           "wlan"},
                {239,           "uwb"},
                {240,           "unknown"},
                {241,           "video_next"},
                {242,           "video_prev"},
                {243,           "brightness_cycle"},
                {244,           "brightness_auto"},
                {245,           "display_off"},
                {246,           "wwan"},
                {247,           "rfkill"},
                {248,           "micmute"},
                {0x100,         "btn_misc"},
                {0x100,         "btn_0"},
                {0x101,         "btn_1"},
                {0x102,         "btn_2"},
                {0x103,         "btn_3"},
                {0x104,         "btn_4"},
                {0x105,         "btn_5"},
                {0x106,         "btn_6"},
                {0x107,         "btn_7"},
                {0x108,         "btn_8"},
                {0x109,         "btn_9"},
                {0x110,         "btn_mouse"},
                {0x110,         "btn_left"},
                {0x111,         "btn_right"},
                {0x112,         "btn_middle"},
                {0x113,         "btn_side"},
                {0x114,         "btn_extra"},
                {0x115,         "btn_forward"},
                {0x116,         "btn_back"},
                {0x117,         "btn_task"},
                {0x120,         "btn_joystick"},
                {0x120,         "btn_trigger"},
                {0x121,         "btn_thumb"},
                {0x122,         "btn_thumb2"},
                {0x123,         "btn_top"},
                {0x124,         "btn_top2"},
                {0x125,         "btn_pinkie"},
                {0x126,         "btn_base"},
                {0x127,         "btn_base2"},
                {0x128,         "btn_base3"},
                {0x129,         "btn_base4"},
                {0x12a,         "btn_base5"},
                {0x12b,         "btn_base6"},
                {0x12f,         "btn_dead"},
                {0x130,         "btn_gamepad"},
                {0x130,         "btn_south"},
                {0x131,         "btn_east"},
                {0x132,         "btn_c"},
                {0x133,         "btn_north"},
                {0x134,         "btn_west"},
                {0x135,         "btn_z"},
                {0x136,         "btn_tl"},
                {0x137,         "btn_tr"},
                {0x138,         "btn_tl2"},
                {0x139,         "btn_tr2"},
                {0x13a,         "btn_select"},
                {0x13b,         "btn_start"},
                {0x13c,         "btn_mode"},
                {0x13d,         "btn_thumbl"},
                {0x13e,         "btn_thumbr"},
                {0x140,         "btn_digi"},
                {0x140,         "btn_tool_pen"},
                {0x141,         "btn_tool_rubber"},
                {0x142,         "btn_tool_brush"},
                {0x143,         "btn_tool_pencil"},
                {0x144,         "btn_tool_airbrush"},
                {0x145,         "btn_tool_finger"},
                {0x146,         "btn_tool_mouse"},
                {0x147,         "btn_tool_lens"},
                {0x148,         "btn_tool_quinttap"},
                {0x14a,         "btn_touch"},
                {0x14b,         "btn_stylus"},
                {0x14c,         "btn_stylus2"},
                {0x14d,         "btn_tool_doubletap"},
                {0x14e,         "btn_tool_tripletap"},
                {0x14f,         "btn_tool_quadtap"},
                {0x150,         "btn_wheel"},
                {0x150,         "btn_gear_down"},
                {0x151,         "btn_gear_up"},
                {0x160,         "ok"},
                {0x161,         "select"},
                {0x162,         "goto"},
                {0x163,         "clear"},
                {0x164,         "power2"},
                {0x165,         "option"},
                {0x166,         "info"},
                {0x167,         "time"},
                {0x168,         "vendor"},
                {0x169,         "archive"},
                {0x16a,         "program"},
                {0x16b,         "channel"},
                {0x16c,         "favorites"},
                {0x16d,         "epg"},
                {0x16e,         "pvr"},
                {0x16f,         "mhp"},
                {0x170,         "language"},
                {0x171,         "title"},
                {0x172,         "subtitle"},
                {0x173,         "angle"},
                {0x174,         "zoom"},
                {0x175,         "mode"},
                {0x176,         "keyboard"},
                {0x177,         "screen"},
                {0x178,         "pc"},
                {0x179,         "tv"},
                {0x17a,         "tv2"},
                {0x17b,         "vcr"},
                {0x17c,         "vcr2"},
                {0x17d,         "sat"},
                {0x17e,         "sat2"},
                {0x17f,         "cd"},
                {0x180,         "tape"},
                {0x181,         "radio"},
                {0x182,         "tuner"},
                {0x183,         "player"},
                {0x184,         "text"},
                {0x185,         "dvd"},
                {0x186,         "aux"},
                {0x187,         "mp3"},
                {0x188,         "audio"},
                {0x189,         "video"},
                {0x18a,         "directory"},
                {0x18b,         "list"},
                {0x18c,         "memo"},
                {0x18d,         "calendar"},
                {0x18e,         "red"},
                {0x18f,         "green"},
                {0x190,         "yellow"},
                {0x191,         "blue"},
                {0x192,         "channelup"},
                {0x193,         "channeldown"},
                {0x194,         "first"},
                {0x195,         "last"},
                {0x196,         "ab"},
                {0x197,         "next"},
                {0x198,         "restart"},
                {0x199,         "slow"},
                {0x19a,         "shuffle"},
                {0x19b,         "break"},
                {0x19c,         "previous"},
                {0x19d,         "digits"},
                {0x19e,         "teen"},
                {0x19f,         "twen"},
                {0x1a0,         "videophone"},
                {0x1a1,         "games"},
                {0x1a2,         "zoomin"},
                {0x1a3,         "zoomout"},
                {0x1a4,         "zoomreset"},
                {0x1a5,         "wordprocessor"},
                {0x1a6,         "editor"},
                {0x1a7,         "spreadsheet"},
                {0x1a8,         "graphicseditor"},
                {0x1a9,         "presentation"},
                {0x1aa,         "database"},
                {0x1ab,         "news"},
                {0x1ac,         "voicemail"},
                {0x1ad,         "addressbook"},
                {0x1ae,         "messenger"},
                {0x1af,         "displaytoggle"},
                {0x1b0,         "spellcheck"},
                {0x1b1,         "logoff"},
                {0x1b2,         "dollar"},
                {0x1b3,         "euro"},
                {0x1b4,         "frameback"},
                {0x1b5,         "frameforward"},
                {0x1b6,         "context_menu"},
                {0x1b7,         "media_repeat"},
                {0x1b8,         "10channelsup"},
                {0x1b9,         "10channelsdown"},
                {0x1ba,         "images"},
                {0x1c0,         "del_eol"},
                {0x1c1,         "del_eos"},
                {0x1c2,         "ins_line"},
                {0x1c3,         "del_line"},
                {0x1d0,         "fn"},
                {0x1d1,         "fn_esc"},
                {0x1d2,         "fn_f1"},
                {0x1d3,         "fn_f2"},
                {0x1d4,         "fn_f3"},
                {0x1d5,         "fn_f4"},
                {0x1d6,         "fn_f5"},
                {0x1d7,         "fn_f6"},
                {0x1d8,         "fn_f7"},
                {0x1d9,         "fn_f8"},
                {0x1da,         "fn_f9"},
                {0x1db,         "fn_f10"},
                {0x1dc,         "fn_f11"},
                {0x1dd,         "fn_f12"},
                {0x1de,         "fn_1"},
                {0x1df,         "fn_2"},
                {0x1e0,         "fn_d"},
                {0x1e1,         "fn_e"},
                {0x1e2,         "fn_f"},
                {0x1e3,         "fn_s"},
                {0x1e4,         "fn_b"},
                {0x1f1,         "brl_dot1"},
                {0x1f2,         "brl_dot2"},
                {0x1f3,         "brl_dot3"},
                {0x1f4,         "brl_dot4"},
                {0x1f5,         "brl_dot5"},
                {0x1f6,         "brl_dot6"},
                {0x1f7,         "brl_dot7"},
                {0x1f8,         "brl_dot8"},
                {0x1f9,         "brl_dot9"},
                {0x1fa,         "brl_dot10"},
                {0x200,         "numeric_0"},
                {0x201,         "numeric_1"},
                {0x202,         "numeric_2"},
                {0x203,         "numeric_3"},
                {0x204,         "numeric_4"},
                {0x205,         "numeric_5"},
                {0x206,         "numeric_6"},
                {0x207,         "numeric_7"},
                {0x208,         "numeric_8"},
                {0x209,         "numeric_9"},
                {0x20a,         "numeric_star"},
                {0x20b,         "numeric_pound"},
                {0x20c,         "numeric_a"},
                {0x20d,         "numeric_b"},
                {0x20e,         "numeric_c"},
                {0x20f,         "numeric_d"},
                {0x210,         "camera_focus"},
                {0x211,         "wps_button"},
                {0x212,         "touchpad_toggle"},
                {0x213,         "touchpad_on"},
                {0x214,         "touchpad_off"},
                {0x215,         "camera_zoomin"},
                {0x216,         "camera_zoomout"},
                {0x217,         "camera_up"},
                {0x218,         "camera_down"},
                {0x219,         "camera_left"},
                {0x21a,         "camera_right"},
                {0x21b,         "attendant_on"},
                {0x21c,         "attendant_off"},
                {0x21d,         "attendant_toggle"},
                {0x21e,         "lights_toggle"},
                {0x220,         "btn_dpad_up"},
                {0x221,         "btn_dpad_down"},
                {0x222,         "btn_dpad_left"},
                {0x223,         "btn_dpad_right"},
                {0x230,         "als_toggle"},
                {0x240,         "buttonconfig"},
                {0x241,         "taskmanager"},
                {0x242,         "journal"},
                {0x243,         "controlpanel"},
                {0x244,         "appselect"},
                {0x245,         "screensaver"},
                {0x246,         "voicecommand"},
                {0x247,         "assistant"},
                {0x250,         "brightness_min"},
                {0x251,         "brightness_max"},
                {0x260,         "kbdinputassist_prev"},
                {0x261,         "kbdinputassist_next"},
                {0x262,         "kbdinputassist_prevgroup"},
                {0x263,         "kbdinputassist_nextgroup"},
                {0x264,         "kbdinputassist_accept"},
                {0x265,         "kbdinputassist_cancel"},
                {0x266,         "right_up"},
                {0x267,         "right_down"},
                {0x268,         "left_up"},
                {0x269,         "left_down"},
                {0x26a,         "root_menu"},
                {0x26b,         "media_top_menu"},
                {0x26c,         "numeric_11"},
                {0x26d,         "numeric_12"},
                {0x26e,         "audio_desc"},
                {0x26f,         "3d_mode"},
                {0x270,         "next_favorite"},
                {0x271,         "stop_record"},
                {0x272,         "pause_record"},
                {0x273,         "vod"},
                {0x274,         "unmute"},
                {0x275,         "fastreverse"},
                {0x276,         "slowreverse"},
                {0x277,         "data"},
                {0x278,         "onscreen_keyboard"},
        };

        static const std::unordered_map<int, std::string> keycodesToEnReprTable = {
                {1,             "esc"},
                {2,             "1"},
                {3,             "2"},
                {4,             "3"},
                {5,             "4"},
                {6,             "5"},
                {7,             "6"},
                {8,             "7"},
                {9,             "8"},
                {10,            "9"},
                {11,            "0"},
                {12,            "minus"},
                {13,            "equal"},
                {14,            "backspace"},
                {15,            "tab"},
                {16,            "q"},
                {17,            "w"},
                {18,            "e"},
                {19,            "r"},
                {20,            "t"},
                {21,            "y"},
                {22,            "u"},
                {23,            "i"},
                {24,            "o"},
                {25,            "p"},
                {26,            "leftbrace"},
                {27,            "rightbrace"},
                {28,            "enter"},
                {29,            "leftctrl"},
                {30,            "a"},
                {31,            "s"},
                {32,            "d"},
                {33,            "f"},
                {34,            "g"},
                {35,            "h"},
                {36,            "j"},
                {37,            "k"},
                {38,            "l"},
                {39,            "semicolon"},
                {40,            "apostrophe"},
                {41,            "grave"},
                {42,            "leftshift"},
                {43,            "backslash"},
                {44,            "z"},
                {45,            "x"},
                {46,            "c"},
                {47,            "v"},
                {48,            "b"},
                {49,            "n"},
                {50,            "m"},
                {51,            "comma"},
                {52,            "dot"},
                {53,            "slash"},
                {54,            "rightshift"},
                {55,            "kpasterisk"},
                {56,            "leftalt"},
                {57,            "space"},
                {58,            "capslock"},
                {59,            "f1"},
                {60,            "f2"},
                {61,            "f3"},
                {62,            "f4"},
                {63,            "f5"},
                {64,            "f6"},
                {65,            "f7"},
                {66,            "f8"},
                {67,            "f9"},
                {68,            "f10"},
                {69,            "numlock"},
                {70,            "scrolllock"},
                {71,            "kp7"},
                {72,            "kp8"},
                {73,            "kp9"},
                {74,            "kpminus"},
                {75,            "kp4"},
                {76,            "kp5"},
                {77,            "kp6"},
                {78,            "kpplus"},
                {79,            "kp1"},
                {80,            "kp2"},
                {81,            "kp3"},
                {82,            "kp0"},
                {83,            "kpdot"},
                {85,            "zenkakuhankaku"},
                {86,            "102nd"},
                {87,            "f11"},
                {88,            "f12"},
                {89,            "ro"},
                {90,            "katakana"},
                {91,            "hiragana"},
                {92,            "henkan"},
                {93,            "katakanahiragana"},
                {94,            "muhenkan"},
                {95,            "kpjpcomma"},
                {96,            "kpenter"},
                {97,            "rightctrl"},
                {98,            "kpslash"},
                {99,            "sysrq"},
                {100,           "rightalt"},
                {101,           "linefeed"},
                {102,           "home"},
                {103,           "up"},
                {104,           "pageup"},
                {105,           "left"},
                {106,           "right"},
                {107,           "end"},
                {108,           "down"},
                {109,           "pagedown"},
                {110,           "insert"},
                {111,           "delete"},
                {112,           "macro"},
                {113,           "mute"},
                {114,           "volumedown"},
                {115,           "volumeup"},
                {116,           "power"},
                {117,           "kpequal"},
                {118,           "kpplusminus"},
                {119,           "pause"},
                {120,           "scale"},
                {121,           "kpcomma"},
                {122,           "hangeul"},
                {123,           "hanja"},
                {124,           "yen"},
                {125,           "leftmeta"},
                {126,           "rightmeta"},
                {127,           "compose"},
                {128,           "stop"},
                {129,           "again"},
                {130,           "props"},
                {131,           "undo"},
                {132,           "front"},
                {133,           "copy"},
                {134,           "open"},
                {135,           "paste"},
                {136,           "find"},
                {137,           "cut"},
                {138,           "help"},
                {139,           "menu"},
                {140,           "calc"},
                {141,           "setup"},
                {142,           "sleep"},
                {143,           "wakeup"},
                {144,           "file"},
                {145,           "sendfile"},
                {146,           "deletefile"},
                {147,           "xfer"},
                {148,           "prog1"},
                {149,           "prog2"},
                {150,           "www"},
                {151,           "msdos"},
                {152,           "coffee"},
                {153,           "rotate_display"},
                {154,           "cyclewindows"},
                {155,           "mail"},
                {156,           "bookmarks"},
                {157,           "computer"},
                {158,           "back"},
                {159,           "forward"},
                {160,           "closecd"},
                {161,           "ejectcd"},
                {162,           "ejectclosecd"},
                {163,           "nextsong"},
                {164,           "playpause"},
                {165,           "previoussong"},
                {166,           "stopcd"},
                {167,           "record"},
                {168,           "rewind"},
                {169,           "phone"},
                {170,           "iso"},
                {171,           "config"},
                {172,           "homepage"},
                {173,           "refresh"},
                {174,           "exit"},
                {175,           "move"},
                {176,           "edit"},
                {177,           "scrollup"},
                {178,           "scrolldown"},
                {179,           "kpleftparen"},
                {180,           "kprightparen"},
                {181,           "new"},
                {182,           "redo"},
                {183,           "f13"},
                {184,           "f14"},
                {185,           "f15"},
                {186,           "f16"},
                {187,           "f17"},
                {188,           "f18"},
                {189,           "f19"},
                {190,           "f20"},
                {191,           "f21"},
                {192,           "f22"},
                {193,           "f23"},
                {194,           "f24"},
                {200,           "playcd"},
                {201,           "pausecd"},
                {202,           "prog3"},
                {203,           "prog4"},
                {204,           "dashboard"},
                {205,           "suspend"},
                {206,           "close"},
                {207,           "play"},
                {208,           "fastforward"},
                {209,           "bassboost"},
                {210,           "print"},
                {211,           "hp"},
                {212,           "camera"},
                {213,           "sound"},
                {214,           "question"},
                {215,           "email"},
                {216,           "chat"},
                {217,           "search"},
                {218,           "connect"},
                {219,           "finance"},
                {220,           "sport"},
                {221,           "shop"},
                {222,           "alterase"},
                {223,           "cancel"},
                {224,           "brightnessdown"},
                {225,           "brightnessup"},
                {226,           "media"},
                {227,           "switchvideomode"},
                {228,           "kbdillumtoggle"},
                {229,           "kbdillumdown"},
                {230,           "kbdillumup"},
                {231,           "send"},
                {232,           "reply"},
                {233,           "forwardmail"},
                {234,           "save"},
                {235,           "documents"},
                {236,           "battery"},
                {237,           "bluetooth"},
                {238,           "wlan"},
                {239,           "uwb"},
                {240,           "unknown"},
                {241,           "video_next"},
                {242,           "video_prev"},
                {243,           "brightness_cycle"},
                {244,           "brightness_auto"},
                {245,           "display_off"},
                {246,           "wwan"},
                {247,           "rfkill"},
                {248,           "micmute"},
                {0x100,         "btn_misc"},
                {0x100,         "btn_0"},
                {0x101,         "btn_1"},
                {0x102,         "btn_2"},
                {0x103,         "btn_3"},
                {0x104,         "btn_4"},
                {0x105,         "btn_5"},
                {0x106,         "btn_6"},
                {0x107,         "btn_7"},
                {0x108,         "btn_8"},
                {0x109,         "btn_9"},
                {0x110,         "btn_mouse"},
                {0x110,         "btn_left"},
                {0x111,         "btn_right"},
                {0x112,         "btn_middle"},
                {0x113,         "btn_side"},
                {0x114,         "btn_extra"},
                {0x115,         "btn_forward"},
                {0x116,         "btn_back"},
                {0x117,         "btn_task"},
                {0x120,         "btn_joystick"},
                {0x120,         "btn_trigger"},
                {0x121,         "btn_thumb"},
                {0x122,         "btn_thumb2"},
                {0x123,         "btn_top"},
                {0x124,         "btn_top2"},
                {0x125,         "btn_pinkie"},
                {0x126,         "btn_base"},
                {0x127,         "btn_base2"},
                {0x128,         "btn_base3"},
                {0x129,         "btn_base4"},
                {0x12a,         "btn_base5"},
                {0x12b,         "btn_base6"},
                {0x12f,         "btn_dead"},
                {0x130,         "btn_gamepad"},
                {0x130,         "btn_south"},
                {0x131,         "btn_east"},
                {0x132,         "btn_c"},
                {0x133,         "btn_north"},
                {0x134,         "btn_west"},
                {0x135,         "btn_z"},
                {0x136,         "btn_tl"},
                {0x137,         "btn_tr"},
                {0x138,         "btn_tl2"},
                {0x139,         "btn_tr2"},
                {0x13a,         "btn_select"},
                {0x13b,         "btn_start"},
                {0x13c,         "btn_mode"},
                {0x13d,         "btn_thumbl"},
                {0x13e,         "btn_thumbr"},
                {0x140,         "btn_digi"},
                {0x140,         "btn_tool_pen"},
                {0x141,         "btn_tool_rubber"},
                {0x142,         "btn_tool_brush"},
                {0x143,         "btn_tool_pencil"},
                {0x144,         "btn_tool_airbrush"},
                {0x145,         "btn_tool_finger"},
                {0x146,         "btn_tool_mouse"},
                {0x147,         "btn_tool_lens"},
                {0x148,         "btn_tool_quinttap"},
                {0x14a,         "btn_touch"},
                {0x14b,         "btn_stylus"},
                {0x14c,         "btn_stylus2"},
                {0x14d,         "btn_tool_doubletap"},
                {0x14e,         "btn_tool_tripletap"},
                {0x14f,         "btn_tool_quadtap"},
                {0x150,         "btn_wheel"},
                {0x150,         "btn_gear_down"},
                {0x151,         "btn_gear_up"},
                {0x160,         "ok"},
                {0x161,         "select"},
                {0x162,         "goto"},
                {0x163,         "clear"},
                {0x164,         "power2"},
                {0x165,         "option"},
                {0x166,         "info"},
                {0x167,         "time"},
                {0x168,         "vendor"},
                {0x169,         "archive"},
                {0x16a,         "program"},
                {0x16b,         "channel"},
                {0x16c,         "favorites"},
                {0x16d,         "epg"},
                {0x16e,         "pvr"},
                {0x16f,         "mhp"},
                {0x170,         "language"},
                {0x171,         "title"},
                {0x172,         "subtitle"},
                {0x173,         "angle"},
                {0x174,         "zoom"},
                {0x175,         "mode"},
                {0x176,         "keyboard"},
                {0x177,         "screen"},
                {0x178,         "pc"},
                {0x179,         "tv"},
                {0x17a,         "tv2"},
                {0x17b,         "vcr"},
                {0x17c,         "vcr2"},
                {0x17d,         "sat"},
                {0x17e,         "sat2"},
                {0x17f,         "cd"},
                {0x180,         "tape"},
                {0x181,         "radio"},
                {0x182,         "tuner"},
                {0x183,         "player"},
                {0x184,         "text"},
                {0x185,         "dvd"},
                {0x186,         "aux"},
                {0x187,         "mp3"},
                {0x188,         "audio"},
                {0x189,         "video"},
                {0x18a,         "directory"},
                {0x18b,         "list"},
                {0x18c,         "memo"},
                {0x18d,         "calendar"},
                {0x18e,         "red"},
                {0x18f,         "green"},
                {0x190,         "yellow"},
                {0x191,         "blue"},
                {0x192,         "channelup"},
                {0x193,         "channeldown"},
                {0x194,         "first"},
                {0x195,         "last"},
                {0x196,         "ab"},
                {0x197,         "next"},
                {0x198,         "restart"},
                {0x199,         "slow"},
                {0x19a,         "shuffle"},
                {0x19b,         "break"},
                {0x19c,         "previous"},
                {0x19d,         "digits"},
                {0x19e,         "teen"},
                {0x19f,         "twen"},
                {0x1a0,         "videophone"},
                {0x1a1,         "games"},
                {0x1a2,         "zoomin"},
                {0x1a3,         "zoomout"},
                {0x1a4,         "zoomreset"},
                {0x1a5,         "wordprocessor"},
                {0x1a6,         "editor"},
                {0x1a7,         "spreadsheet"},
                {0x1a8,         "graphicseditor"},
                {0x1a9,         "presentation"},
                {0x1aa,         "database"},
                {0x1ab,         "news"},
                {0x1ac,         "voicemail"},
                {0x1ad,         "addressbook"},
                {0x1ae,         "messenger"},
                {0x1af,         "displaytoggle"},
                {0x1b0,         "spellcheck"},
                {0x1b1,         "logoff"},
                {0x1b2,         "dollar"},
                {0x1b3,         "euro"},
                {0x1b4,         "frameback"},
                {0x1b5,         "frameforward"},
                {0x1b6,         "context_menu"},
                {0x1b7,         "media_repeat"},
                {0x1b8,         "10channelsup"},
                {0x1b9,         "10channelsdown"},
                {0x1ba,         "images"},
                {0x1c0,         "del_eol"},
                {0x1c1,         "del_eos"},
                {0x1c2,         "ins_line"},
                {0x1c3,         "del_line"},
                {0x1d0,         "fn"},
                {0x1d1,         "fn_esc"},
                {0x1d2,         "fn_f1"},
                {0x1d3,         "fn_f2"},
                {0x1d4,         "fn_f3"},
                {0x1d5,         "fn_f4"},
                {0x1d6,         "fn_f5"},
                {0x1d7,         "fn_f6"},
                {0x1d8,         "fn_f7"},
                {0x1d9,         "fn_f8"},
                {0x1da,         "fn_f9"},
                {0x1db,         "fn_f10"},
                {0x1dc,         "fn_f11"},
                {0x1dd,         "fn_f12"},
                {0x1de,         "fn_1"},
                {0x1df,         "fn_2"},
                {0x1e0,         "fn_d"},
                {0x1e1,         "fn_e"},
                {0x1e2,         "fn_f"},
                {0x1e3,         "fn_s"},
                {0x1e4,         "fn_b"},
                {0x1f1,         "brl_dot1"},
                {0x1f2,         "brl_dot2"},
                {0x1f3,         "brl_dot3"},
                {0x1f4,         "brl_dot4"},
                {0x1f5,         "brl_dot5"},
                {0x1f6,         "brl_dot6"},
                {0x1f7,         "brl_dot7"},
                {0x1f8,         "brl_dot8"},
                {0x1f9,         "brl_dot9"},
                {0x1fa,         "brl_dot10"},
                {0x200,         "numeric_0"},
                {0x201,         "numeric_1"},
                {0x202,         "numeric_2"},
                {0x203,         "numeric_3"},
                {0x204,         "numeric_4"},
                {0x205,         "numeric_5"},
                {0x206,         "numeric_6"},
                {0x207,         "numeric_7"},
                {0x208,         "numeric_8"},
                {0x209,         "numeric_9"},
                {0x20a,         "numeric_star"},
                {0x20b,         "numeric_pound"},
                {0x20c,         "numeric_a"},
                {0x20d,         "numeric_b"},
                {0x20e,         "numeric_c"},
                {0x20f,         "numeric_d"},
                {0x210,         "camera_focus"},
                {0x211,         "wps_button"},
                {0x212,         "touchpad_toggle"},
                {0x213,         "touchpad_on"},
                {0x214,         "touchpad_off"},
                {0x215,         "camera_zoomin"},
                {0x216,         "camera_zoomout"},
                {0x217,         "camera_up"},
                {0x218,         "camera_down"},
                {0x219,         "camera_left"},
                {0x21a,         "camera_right"},
                {0x21b,         "attendant_on"},
                {0x21c,         "attendant_off"},
                {0x21d,         "attendant_toggle"},
                {0x21e,         "lights_toggle"},
                {0x220,         "btn_dpad_up"},
                {0x221,         "btn_dpad_down"},
                {0x222,         "btn_dpad_left"},
                {0x223,         "btn_dpad_right"},
                {0x230,         "als_toggle"},
                {0x240,         "buttonconfig"},
                {0x241,         "taskmanager"},
                {0x242,         "journal"},
                {0x243,         "controlpanel"},
                {0x244,         "appselect"},
                {0x245,         "screensaver"},
                {0x246,         "voicecommand"},
                {0x247,         "assistant"},
                {0x250,         "brightness_min"},
                {0x251,         "brightness_max"},
                {0x260,         "kbdinputassist_prev"},
                {0x261,         "kbdinputassist_next"},
                {0x262,         "kbdinputassist_prevgroup"},
                {0x263,         "kbdinputassist_nextgroup"},
                {0x264,         "kbdinputassist_accept"},
                {0x265,         "kbdinputassist_cancel"},
                {0x266,         "right_up"},
                {0x267,         "right_down"},
                {0x268,         "left_up"},
                {0x269,         "left_down"},
                {0x26a,         "root_menu"},
                {0x26b,         "media_top_menu"},
                {0x26c,         "numeric_11"},
                {0x26d,         "numeric_12"},
                {0x26e,         "audio_desc"},
                {0x26f,         "3d_mode"},
                {0x270,         "next_favorite"},
                {0x271,         "stop_record"},
                {0x272,         "pause_record"},
                {0x273,         "vod"},
                {0x274,         "unmute"},
                {0x275,         "fastreverse"},
                {0x276,         "slowreverse"},
                {0x277,         "data"},
                {0x278,         "onscreen_keyboard"},
        };
}
